name: pack-release-package
run-name: Triggered by ${{ github.actor }}

on:
  push:
    tags:
      - '*'

jobs:
  pack-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Get full Version
        run: . source_versions.sh && echo PACKAGE_VERSION=${BATS_CORE_VERSION}-${{ github.run_number }} >> $GITHUB_ENV
      - name: build
        run: BUILD_NUMBER=${{ github.run_number }} ./build
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ env.PACKAGE_VERSION }}
          tag_name: ${{ github.ref }}
          body_path: source_versions.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bats-all.tar.gz
          asset_name: bats-all.tar.gz
          asset_content_type: application/gzip
