name: pack-release-package
run-name: Triggered by ${{ github.actor }}

on:
  push:
    branches:
      - main

jobs:
  pack-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: full_version
        run: . source_versions.sh && echo ${BATS_CORE_VERSION}-${{ github.run_number }}
        id: version
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: BUILD_NUMBER=${{ github.run_number }} ./build
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.full_version.outputs.version }}
#          tag_name: ${{ github.ref }}
          body_path: source_versions.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .build/dst/bats-all-${{ steps.full_version.outputs.version }}.tar.gz
          asset_name: bats-all.tar.gz
          asset_content_type: application/gzip
